// Wykies Admin JS
const ALLOWLIST_EMAIL = 'wykiesautomation@gmail.com';
const GAS_BASE = 'https://script.google.com/macros/s/REPLACE_WITH_DEPLOY_ID/exec';
const SHEET_ID = '12qRMe6pAPVaQtosZBnhVtpMwyNks7W8uY9PX1mF620k';
const tabs = ['dashboard','catalog','prices','payments','pages','settings','audit'];
function showTab(id){ tabs.forEach(t=>{ document.querySelector(`#tab-${t}`).classList.toggle('hidden', t!==id); document.querySelector(`[data-tab="${t}"]`).classList.toggle('active', t===id); }); }
let currentUser = null;
function onCredential(response){ try{ const decoded = parseJwt(response.credential); const email = decoded.email; if(email && email.toLowerCase()===ALLOWLIST_EMAIL){ currentUser = {email, name: decoded.name}; document.getElementById('userEmail').textContent = email; document.getElementById('userBox').classList.remove('hidden'); document.getElementById('signin').classList.add('hidden'); initData(); } else { document.getElementById('accessDenied').classList.remove('hidden'); } }catch(err){ console.error(err); } }
function parseJwt (token) { const base64Url = token.split('.')[1]; const base64 = base64Url.replace(/-/g,'+').replace(/_/g,'/'); const jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c){ return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2); }).join('')); return JSON.parse(jsonPayload); }
function initGIS(){ window.google && google.accounts.id.initialize({ client_id: 'REPLACE_WITH_OAUTH_CLIENT_ID', callback: onCredential }); const btn = document.getElementById('googleBtn'); btn.addEventListener('click', ()=>google.accounts.id.prompt()); }
function renderPreview(){ const md = document.getElementById('pageContent').value || ''; const html = marked.parse(md); document.getElementById('pagePreview').innerHTML = DOMPurify.sanitize(html); }
async function gas(action, payload={}){ const url = GAS_BASE + `?action=${encodeURIComponent(action)}&sheet=${encodeURIComponent(SHEET_ID)}`; const res = await fetch(url, {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({user: currentUser, payload})}); if(!res.ok){ throw new Error('GAS error '+res.status); } return await res.json(); }
async function initData(){ try{ showTab('dashboard'); const dash = await gas('dashboard'); document.getElementById('salesToday').textContent = dash.salesToday || 'R 0'; document.getElementById('itnCount').textContent = dash.itn24h || 0; document.getElementById('queueHealth').textContent = dash.queueHealth || 'OK'; const products = await gas('listProducts'); renderCatalog(products); const priceLog = await gas('listPriceLog'); renderPriceLog(priceLog); const payments = await gas('listPayments'); renderPayments(payments); const settings = await gas('getSettings'); applySettings(settings); const audit = await gas('listAudit'); renderAudit(audit); }catch(err){ console.error(err); } }
function renderCatalog(items){ const tbody = document.querySelector('#catalogTable tbody'); tbody.innerHTML=''; (items||[]).forEach(p=>{ const tr = document.createElement('tr'); tr.innerHTML = `<td>${p.id}</td><td>${p.name}</td><td>R ${p.price}</td><td>${(p.images||[]).length}</td><td>${p.status||'active'}</td><td><button class='btn secondary' data-id='${p.id}' data-act='edit'>Edit</button><button class='btn warn' data-id='${p.id}' data-act='price'>Change Price</button></td>`; tbody.appendChild(tr); }); }
function renderPriceLog(rows){ const tbody = document.querySelector('#priceLogTable tbody'); tbody.innerHTML=''; (rows||[]).forEach(r=>{ const tr = document.createElement('tr'); tr.innerHTML = `<td>${r.product_id}</td><td>R ${r.old}</td><td>R ${r.new}</td><td>${r.who}</td><td>${r.when}</td><td>${r.note||''}</td>`; tbody.appendChild(tr); }); }
function renderPayments(rows){ const tbody = document.querySelector('#paymentsTable tbody'); tbody.innerHTML=''; (rows||[]).forEach(r=>{ const tr = document.createElement('tr'); tr.innerHTML = `<td>${r.date}</td><td>${r.order}</td><td>${r.email}</td><td>R ${r.total}</td><td>${r.status}</td><td><button class='btn secondary' data-id='${r.order}' data-act='resend'>Resend Invoice</button></td>`; tbody.appendChild(tr); }); }
function applySettings(s){ if(!s) return; document.getElementById('companyName').value = s.companyName||''; document.getElementById('vatNumber').value = s.vatNumber||''; document.getElementById('registeredAddress').value = s.registeredAddress||''; document.getElementById('supportEmail').value = s.supportEmail||''; if(s.brandColor){ document.documentElement.style.setProperty('--brand-blue', s.brandColor); document.getElementById('brandColor').value = s.brandColor; } }
function renderAudit(rows){ const tbody = document.querySelector('#auditTable tbody'); tbody.innerHTML=''; (rows||[]).forEach(r=>{ const tr = document.createElement('tr'); tr.innerHTML = `<td>${r.when}</td><td>${r.who}</td><td>${r.event}</td><td>${r.detail||''}</td>`; tbody.appendChild(tr); }); }
window.addEventListener('DOMContentLoaded', ()=>{ document.querySelectorAll('#nav a').forEach(a=>{ a.addEventListener('click', (e)=>{ e.preventDefault(); showTab(a.dataset.tab); }); }); document.getElementById('btnPreview').addEventListener('click', renderPreview); renderPreview(); document.getElementById('btnSaveSettings').addEventListener('click', async ()=>{ const s = { companyName: document.getElementById('companyName').value, vatNumber: document.getElementById('vatNumber').value, registeredAddress: document.getElementById('registeredAddress').value, supportEmail: document.getElementById('supportEmail').value, brandColor: document.getElementById('brandColor').value }; await gas('saveSettings', s); applySettings(s); }); document.getElementById('btnSavePage').addEventListener('click', async ()=>{ const p = { slug: document.getElementById('pageSlug').value, title: document.getElementById('pageTitle').value, content: document.getElementById('pageContent').value }; await gas('savePage', p); renderPreview(); }); document.getElementById('signOut').addEventListener('click', ()=>{ google.accounts.id.disableAutoSelect(); currentUser = null; document.getElementById('userBox').classList.add('hidden'); document.getElementById('signin').classList.remove('hidden'); }); document.getElementById('signin').classList.remove('hidden'); initGIS(); });
