// Wykies Automation — Admin front-end (token enforced)
let BACKEND_URL = '';
const DEFAULT_ADMIN_EMAIL = 'wykiesautomation@gmail.com';
const ROUTES = ['login','products','gallery','dashboard'];
function $(id){ return document.getElementById(id); }
function show(id, on=true){ const el=$(id); if(el) el.style.display = on?'':'none'; }
function setText(id, t, color){ const el=$(id); if(!el) return; el.textContent=t; if(color) el.style.color=color; }
function value(id){ const el=$(id); return el?el.value:''; }
function setValue(id,v){ const el=$(id); if(el) el.value=v; }
function getToken(){ return localStorage.getItem('wa_admin_token')||''; }
function setToken(t){ localStorage.setItem('wa_admin_token', t); }
function clearToken(){ localStorage.removeItem('wa_admin_token'); }
function decodeTokenPayload(token){ try{ const parts=token.split('.'); if(parts.length!==3) return null; const b64=parts[1].replace(/-/g,'+').replace(/_/g,'/'); const json=atob(b64); return JSON.parse(json);}catch(e){ return null; }}
function isTokenValid(){ const t=getToken(); const p=decodeTokenPayload(t); if(!p||!p.exp) return false; const now=Math.floor(Date.now()/1000); return p.exp>now; }
async function apiGet(action, params={}){ const qs = new URLSearchParams({ action, ...params }); const url=`${BACKEND_URL}?${qs.toString()}`; console.log('GET',url); const res = await fetch(url, { method:'GET' }); const json = await res.json().catch(()=>({ok:false,error:'Bad JSON'})); console.log('RESP',action,json); return json; }
async function apiPost(action, data={}){ const body = { ...data }; const t=getToken(); if(t) body.token=t; const url=`${BACKEND_URL}?action=${encodeURIComponent(action)}`; console.log('POST',url, body); const res = await fetch(url, { method:'POST', headers:{ 'Content-Type':'application/json' }, body: JSON.stringify(body) }); const json = await res.json().catch(()=>({ok:false,error:'Bad JSON'})); console.log('RESP',action,json); return json; }
function showSignedInUI(emailText=''){ show('password-row', false); show('btn-login', false); show('signed-badge', true); setText('login-status', emailText?`Signed in as ${emailText}`:'Signed in.', '#8bc34a'); }
function showSignedOutUI(msg='Please sign in.'){ show('password-row', true); show('btn-login', true); show('signed-badge', false); setText('login-status', msg, '#ccc'); }
function showRoute(name){ ROUTES.forEach(r=>{ const el=$(r); if(el) el.style.display = (r===name)?'':'none'; }); document.querySelectorAll('nav a[href^="#"]').forEach(a=>{ const target=a.getAttribute('href').replace('#',''); a.classList.toggle('active', target===name); }); }
function isAuthed(){ return isTokenValid(); }
function guardRoute(name){ const adminRoutes=['products','gallery','dashboard']; if(adminRoutes.includes(name) && !isAuthed()){ showRoute('login'); setText('login-status','Please sign in to access admin.','#ff7043'); return false; } return true; }
function navigateTo(name){ if(!ROUTES.includes(name)) name='login'; if(!guardRoute(name)) return; showRoute(name); if(name==='dashboard') refreshDashboard(); if(name==='products') renderProducts(); if(name==='gallery') renderImages(); }
async function refreshDashboard(){ setText('dash-logged-in', isAuthed()? 'Yes':'No'); try{ const p=await apiGet('products'); if(p.ok) setText('dash-products-count', String((p.products||[]).length)); }catch(e){} try{ const g=await apiGet('images'); if(g.ok) setText('dash-images-count', String((g.images||[]).length)); }catch(e){} }
function signOut(){ clearToken(); showSignedOutUI('Signed out.'); navigateTo('login'); const pl=$('products-list'); if(pl) pl.innerHTML=''; const il=$('images-list'); if(il) il.innerHTML=''; }
function wireNav(){ document.querySelectorAll('nav a[href^="#"]').forEach(a=>{ a.addEventListener('click', ev=>{ ev.preventDefault(); const t=a.getAttribute('href').replace('#',''); navigateTo(t); history.replaceState(null,'','#'+t); }); }); const so=$('btn-signout'); if(so) so.addEventListener('click', signOut); }
async function initAdminAuth(){ if($('admin-email') && !value('admin-email')) setValue('admin-email', DEFAULT_ADMIN_EMAIL); if(isTokenValid()){ try{ const out=await apiGet('admin_status', { token:getToken() }); if(out && out.ok){ showSignedInUI(out.email||DEFAULT_ADMIN_EMAIL); return; } }catch(e){} } showSignedOutUI(); }
async function handleLoginClick(){ const email=(value('admin-email').trim()||DEFAULT_ADMIN_EMAIL); const pass=value('admin-pass'); setText('login-status','Signing in…','#ccc'); try{ const out=await apiPost('login', { email, pass }); if(out.ok && out.token){ setToken(out.token); showSignedInUI(email); navigateTo('dashboard'); refreshDashboard(); } else { clearToken(); showSignedOutUI('Login failed: '+(out.message||out.error||'unknown')); } }catch(err){ clearToken(); showSignedOutUI('Login error: '+(err && err.message ? err.message : String(err))); } }
function setActionButtonsEnabled(enabled){ ['btn-save-product','btn-add-image'].forEach(id=>{ const b=$(id); if(b){ b.disabled=!enabled; b.classList.toggle('disabled', !enabled); }}); }
async function saveProductFromUI(){ if(!isTokenValid()){ setText('save-product-status','Invalid or expired token. Redirecting to Login…','#ff7043'); navigateTo('login'); return; } const data={ id:(value('p-id')||'').trim(), name:(value('p-name')||'').trim(), price:Number(value('p-price')||0), desc:(value('p-desc')||'').trim() }; if(!data.id || !data.name){ setText('save-product-status','Missing id or name.','#ff7043'); return; } try{ const out=await apiPost('save_product', data); if(out.ok){ setText('save-product-status','Saved.','#8bc34a'); renderProducts(); } else { setText('save-product-status','Error: '+(out.error||out.message),'#ff7043'); }} catch(err){ setText('save-product-status','Save error: '+String(err),'#ff7043'); } }
async function addImageFromUI(){ if(!isTokenValid()){ setText('add-image-status','Invalid or expired token. Redirecting to Login…','#ff7043'); navigateTo('login'); return; } const data={ url:(value('img-url')||'').trim(), alt:(value('img-alt')||'').trim() }; if(!data.url){ setText('add-image-status','Missing image URL.','#ff7043'); return; } try{ const out=await apiPost('add_image', data); if(out.ok){ setText('add-image-status','Added.','#8bc34a'); renderImages(); } else { setText('add-image-status','Error: '+(out.error||out.message),'#ff7043'); }} catch(err){ setText('add-image-status','Add error: '+String(err),'#ff7043'); } }
function escapeHtml(s){ return String(s||'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',''':'&#39;'}[c])); }
function escapeAttr(s){ return String(s||'').replace(/"/g,'&quot;'); }
async function renderProducts(){ const host=$('products-list'); if(!host) return; host.innerHTML='Loading products…'; try{ const out=await apiGet('products'); if(out.ok && Array.isArray(out.products)){ host.innerHTML = out.products.map(p=>`<li><strong>${escapeHtml(p.name)}</strong> (ID: ${escapeHtml(p.id)}) — R${Number(p.price||0).toFixed(2)}<br><small>${escapeHtml(p.desc||'')}</small></li>`).join('') || '<li>No products.</li>'; } else host.innerHTML='<li>Error loading products.</li>'; } catch(e){ host.innerHTML='<li>Error loading products.</li>'; } }
async function renderImages(){ const host=$('images-list'); if(!host) return; host.innerHTML='Loading images…'; try{ const out=await apiGet('images'); if(out.ok && Array.isArray(out.images)){ host.innerHTML = out.images.map(img=>`<li><a href="${escapeAttr(img.url)}" target="_blank">${escapeHtml(img.alt||img.url)}</a></li>`).join('') || '<li>No images.</li>'; } else host.innerHTML='<li>Error loading images.</li>'; } catch(e){ host.innerHTML='<li>Error loading images.</li>'; } }
function wireEvents(){ if($('btn-login')) $('btn-login').addEventListener('click', handleLoginClick); if($('btn-save-product')) $('btn-save-product').addEventListener('click', saveProductFromUI); if($('btn-add-image')) $('btn-add-image').addEventListener('click', addImageFromUI); }
async function loadConfig(){ try{ const res = await fetch('config.json'); const cfg = await res.json(); BACKEND_URL = cfg.BACKEND_URL; console.log('BACKEND_URL', BACKEND_URL); } catch(e){ console.error('Failed to load config.json', e); }}
window.addEventListener('DOMContentLoaded', async ()=>{ await loadConfig(); wireEvents(); await initAdminAuth(); setActionButtonsEnabled(isAuthed()); (function initRouting(){ wireNav(); const initial=(location.hash||'#login').replace('#',''); if(isAuthed()){ showSignedInUI(DEFAULT_ADMIN_EMAIL); navigateTo(initial==='login'?'dashboard':initial); } else { showSignedOutUI(); navigateTo('login'); } })(); renderProducts(); renderImages(); });
