
(function(){
  const $  = (sel,ctx=document)=>ctx.querySelector(sel);
  const $$ = (sel,ctx=document)=>Array.from(ctx.querySelectorAll(sel));
  const state = { config:null, role:'Viewer', paymentsCache:[], logsCache:[], galleryCache:[] };
  async function loadConfig(){ if(state.config) return state.config; const res = await fetch('./config/config.json').catch(()=>fetch('./config/config.example.json')); state.config = await res.json(); return state.config; }
  async function fetchJson(path, params={}, opts={}){ const {scriptUrl} = await loadConfig(); const usp = new URLSearchParams(params); const token = localStorage.getItem('adminToken'); const body = opts.body ? { ...opts.body, token } : undefined; const url = `${scriptUrl}${path}${usp.toString()?`?${usp.toString()}`:''}${token?`${usp.toString()?'&':'?'}token=${encodeURIComponent(token)}`:''}`; const res = await fetch(url, { method: opts.method||'GET', headers: { 'Content-Type':'application/json' }, body: body ? JSON.stringify(body) : undefined }); const data = await res.json(); if(!data.ok) throw new Error(data.error?.message||'Request failed'); return data.data; }
  async function getSession(){ try{ const data = await fetchJson('/auth/session'); state.role = (data.role||'Viewer'); $('#roleBadge').textContent = state.role; document.body.classList.toggle('gate-viewer', state.role!=='Admin'); } catch(e){ state.role='Viewer'; $('#roleBadge').textContent = 'Viewer'; document.body.classList.add('gate-viewer'); } }
  function showToast(type,msg){ const host = document.getElementById('toasts'); if(!host) return; const el = document.createElement('div'); el.className = `toast ${type}`; el.textContent = msg; host.appendChild(el); setTimeout(()=>{ el.remove(); }, 4000); }
  function switchTab(id){ $$('.sidenav button').forEach(b=>b.classList.toggle('active', b.dataset.tab===id)); $$('.tab').forEach(t=>t.classList.toggle('visible', t.id===`tab-${id}`)); }
  function setStatus(msg, ok=true){ const sb = $('#statusbar'); sb.textContent = msg; sb.style.color = ok ? '#b7c8dc' : '#ff8080'; }
  function downloadCSV(filename, rows){ const headers = Object.keys(rows[0]||{}); const lines = [headers.join(',')].concat(rows.map(r=>headers.map(h=>JSON.stringify(r[h]??'')).join(','))); const blob = new Blob([lines.join('\n')], {type:'text/csv'}); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = filename; a.click(); URL.revokeObjectURL(a.href); }
  async function loadOverview(){ try{ const today = new Date().toISOString().slice(0,10); const [products, gallery, payments, prices] = await Promise.all([ fetchJson('/products'), fetchJson('/gallery'), fetchJson('/payments',{from:today,to:today}), fetchJson('/logs',{type:'price'}) ]); $('#stat-products').textContent = products.length; $('#stat-gallery').textContent = gallery.length; $('#stat-payments').textContent = payments.length; $('#stat-errors').textContent = 0; state.paymentsCache = payments; state.logsCache = prices; const smallTable = (rows, cols)=>`<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${r[c]??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; $('#ov-products').innerHTML = smallTable(products.slice(0,5), ['sku','name','price_incl','active']); $('#ov-payments').innerHTML = smallTable(payments.slice(0,3), ['timestamp','invoiceNo','email']); $('#ov-price').innerHTML = smallTable(prices.slice(0,5), ['timestamp','sku','oldPrice','newPrice','changedBy']); $('#ov-gallery').innerHTML = (gallery.slice(0,6)).map(g=>`<img src="${g.thumbUrl}" alt="${g.name}" style="height:72px;border-radius:8px;border:1px solid #1b2430;margin:6px;"/>`).join(''); $('#exp-pay').onclick = ()=>downloadCSV('payments_today.csv', payments); $('#exp-price').onclick = ()=>downloadCSV('price_changes.csv', prices); setStatus('Connected to Google Sheets CMS'); } catch(e){ setStatus('Failed to load overview: '+e.message,false); } }
  async function loadProducts(){ try{ const rows = await fetchJson('/products'); const table = `<table><thead><tr><th>SKU</th><th>Name</th><th>Price (incl.)</th><th>Summary</th><th>Active</th><th></th></tr></thead><tbody>`+
    rows.map(r=>`<tr data-sku="${r.sku}"><td class="mono">${r.sku}</td><td><input type="text" class="name-input" value="${(r.name||'').replace(/"/g,'\"')}" data-old="${(r.name||'').replace(/"/g,'\"')}"/></td><td><input type="number" step="1" min="0" class="price-input" value="${r.price_incl}" data-old="${r.price_incl}"/></td><td>${r.summary||''}</td><td><input type="checkbox" class="active-toggle" ${r.active?'checked':''}/></td><td><button data-edit>Edit</button></td></tr>`).join('')+`</tbody></table>`; $('#products-table').innerHTML = table;
    $('#products-table').addEventListener('change', async (e)=>{
      const nameInp = e.target.closest('.name-input'); if(nameInp){ const tr = nameInp.closest('tr'); const sku = tr.dataset.sku; const oldVal = nameInp.dataset.old; const newVal = nameInp.value.trim(); if(newVal===oldVal) return; if(state.role!=='Admin'){ nameInp.value = oldVal; return; } nameInp.disabled = true; try{ await fetchJson('/products/update', {}, { method:'POST', body:{ sku, patch:{ name: newVal } } }); nameInp.dataset.old = newVal; showToast('success', `Name updated for ${sku}`);}catch(err){ showToast('error','Save failed: '+err.message); nameInp.value = oldVal;} finally{ nameInp.disabled = false; }}
      const priceInp = e.target.closest('.price-input'); if(priceInp){ const tr = priceInp.closest('tr'); const sku = tr.dataset.sku; const oldVal = parseFloat(priceInp.dataset.old); const newVal = parseFloat(priceInp.value); if(Number.isNaN(newVal) || newVal<0){ showToast('error','Invalid price'); priceInp.value=oldVal; return; } if(newVal===oldVal) return; if(state.role!=='Admin'){ priceInp.value=oldVal; return; } if(!confirm(`Change price for ${sku} from R${oldVal} to R${newVal}?\nThis will be logged in PriceChanges.`)){ priceInp.value=oldVal; return; } priceInp.disabled=true; try{ await fetchJson('/products/update', {}, { method:'POST', body:{ sku, patch:{ price_incl:newVal } } }); priceInp.dataset.old = String(newVal); showToast('success', `Price updated for ${sku}`);}catch(err){ showToast('error','Save failed: '+err.message); priceInp.value=oldVal;} finally{ priceInp.disabled=false; }}
      const activeChk = e.target.closest('.active-toggle'); if(activeChk){ const tr = activeChk.closest('tr'); const sku = tr.dataset.sku; const val = activeChk.checked; if(state.role!=='Admin'){ activeChk.checked=!val; return; } activeChk.disabled=true; try{ await fetchJson('/products/toggle', {}, { method:'POST', body:{ sku, active: val } }); showToast('success', `${sku} ${val?'activated':'deactivated'}`);}catch(err){ showToast('error','Toggle failed: '+err.message); activeChk.checked=!val;} finally{ activeChk.disabled=false; }}
    });
    $('#add-product').addEventListener('click', ()=>{
      if(state.role!=='Admin') return;
      const m = $('#modal'); m.classList.remove('hidden');
      m.innerHTML = `<div class="panel"><h3>Add Product</h3><div class="form">
        <label>SKU <input id="ap-sku" placeholder="WA-01"/></label>
        <label>Name <input id="ap-name"/></label>
        <label>Price (incl.) <input id="ap-price" type="number" min="0" step="1"/></label>
        <label>Summary <input id="ap-summary"/></label>
        <label>Description (MD) <textarea id="ap-desc" rows="4"></textarea></label>
        <label>Image URL <input id="ap-img"/></label>
        <label>Trial URL <input id="ap-trial"/></label>
        <label>Docs URL <input id="ap-doc"/></label>
        <label><input id="ap-active" type="checkbox" checked/> Active</label>
      </div><div style="display:flex;gap:8px;justify-content:flex-end"><button id="ap-cancel" class="btn">Cancel</button><button id="ap-save" class="btn btn-primary">Save</button></div></div>`;
      $('#ap-cancel').onclick = ()=>{ m.classList.add('hidden'); m.innerHTML=''; };
      $('#ap-save').onclick = async ()=>{
        const sku = $('#ap-sku').value.trim().toUpperCase();
        const name = $('#ap-name').value.trim();
        const price = parseFloat($('#ap-price').value);
        const summary = $('#ap-summary').value.trim();
        const description_md = $('#ap-desc').value;
        const imageUrl = $('#ap-img').value.trim();
        const trialUrl = $('#ap-trial').value.trim();
        const docUrl = $('#ap-doc').value.trim();
        const active = $('#ap-active').checked;
        if(!/^WA-\d{2}$/.test(sku)){ showToast('error','SKU must be WA-XX'); return; }
        if(!name || Number.isNaN(price) || price<0){ showToast('error','Name/price invalid'); return; }
        try{
          await fetchJson('/products/create', {}, { method:'POST', body:{ sku, name, price_incl: price, summary, description_md, imageUrl, trialUrl, docUrl, active } });
          m.classList.add('hidden'); m.innerHTML=''; showToast('success', `Product ${sku} created`);
          await loadProducts();
        }catch(err){ showToast('error','Create failed: '+err.message); }
      };
    });
  }catch(e){ setStatus('Products load failed: '+e.message,false); }}
  async function loadGallery(){ try{ const rows = await fetchJson('/gallery'); state.galleryCache = rows; const grid = $('#gallery-grid'); grid.innerHTML = rows.map(x=>`<div class="card" draggable="true" data-id="${x.id||x.filename||x.imageUrl}"><img src="${x.thumbUrl}" alt="${x.name}" style="width:100%;height:120px;object-fit:cover;border-radius:8px;border:1px solid #1b2430"><div>${x.caption||''}</div></div>`).join(''); let dragEl = null; grid.addEventListener('dragstart', e=>{ const c = e.target.closest('.card'); if(!c) return; dragEl = c; c.classList.add('dragging'); }); grid.addEventListener('dragend', e=>{ const c = e.target.closest('.card'); if(c) c.classList.remove('dragging'); dragEl = null; }); grid.addEventListener('dragover', e=>{ e.preventDefault(); const c = e.target.closest('.card'); if(!c || c===dragEl) return; const rect = c.getBoundingClientRect(); const after = (e.clientY - rect.top) > rect.height/2; grid.insertBefore(dragEl, after ? c.nextSibling : c); }); $('#upload-img').onclick = async ()=>{ if(state.role!=='Admin'){ return; } const fileInput = $('#upload-file'); const file = fileInput.files && fileInput.files[0]; if(!file){ showToast('error','Choose a PNG/WebP file first'); return; } if(file.size > 200*1024){ showToast('error','File too large (>200KB)'); return; } try{ const init = await fetchJson('/gallery/uploadInit', { filename: file.name, mime: file.type }); if(init.uploadUrl){ await fetch(init.uploadUrl, { method:'PUT', headers:{'Content-Type': file.type}, body: file }); } await fetchJson('/gallery/create', {}, { method:'POST', body:{ filename: init.filename||file.name, caption: '', orderIndex: (state.galleryCache.length+1), active: true } }); showToast('success','Image uploaded'); await loadGallery(); }catch(err){ showToast('error','Upload failed: '+err.message); } }; $('#save-order').onclick = async ()=>{ if(state.role!=='Admin'){ return; } const ids = $$('.card', grid).map(c=>c.dataset.id); try{ await fetchJson('/gallery/reorder', {}, { method:'POST', body:{ ids } }); showToast('success','Order saved'); } catch(err){ showToast('error','Save order failed: '+err.message); } }; }catch(e){ setStatus('Gallery load failed: '+e.message,false); }}
  function currency(z){ return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(z); }
  async function loadPayments(){ try{ const from = $('#pay-from').value || new Date().toISOString().slice(0,10); const to = $('#pay-to').value || new Date().toISOString().slice(0,10); const email = $('#pay-email').value || ''; const sku = $('#pay-sku').value || ''; const rows = await fetchJson('/payments',{from,to,email,sku}); state.paymentsCache = rows; const table = `<table><thead><tr><th>Timestamp</th><th>InvoiceNo</th><th>Email</th><th>SKU</th><th>Total</th><th></th></tr></thead><tbody>`+
    rows.map(r=>`<tr data-inv="${r.invoiceNo}"><td>${r.timestamp}</td><td>${r.invoiceNo}</td><td>${r.email}</td><td>${r.sku}</td><td>${currency(r.total_incl_vat||r.totalInclVAT)}</td><td><button data-resend ${state.role!=='Admin'?'disabled':''}>Resend Invoice</button></td></tr>`).join('')+`</tbody></table>`; $('#payments-table').innerHTML = table; $('#payments-table').addEventListener('click', async e=>{ const btn = e.target.closest('button[data-resend]'); if(!btn) return; const row = btn.closest('tr'); const invoiceNo = row.dataset.inv; if(!confirm(`Resend invoice ${invoiceNo}?`)) return; try{ await fetchJson('/payments/resend-invoice', {}, {method:'POST',body:{invoiceNo}}); showToast('success','Invoice resent'); } catch(err){ showToast('error','Resend failed: '+err.message); } }, { once:true }); $('#pay-export').onclick = ()=>{ if(state.paymentsCache.length) downloadCSV('payments.csv', state.paymentsCache); else showToast('info','No payments to export'); }; }catch(e){ setStatus('Payments load failed: '+e.message,false); }}
  async function loadLogs(kind='price'){ try{ const rows = await fetchJson('/logs',{type:kind}); state.logsCache = rows; const colsBy = { price:['timestamp','sku','oldPrice','newPrice','changedBy','sourceIP'], system:['timestamp','level','component','message'], itn:['timestamp','message','sourceIP'] }; const cols = colsBy[kind]||colsBy.price; const table = `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>`+ rows.map(r=>`<tr>${cols.map(c=>`<td>${r[c]??''}</td>`).join('')}</tr>`).join('') +`</tbody></table>`; $('#logs-table').innerHTML = table; $('#logs-export').onclick = ()=>{ if(state.logsCache.length) downloadCSV(`logs_${kind}.csv`, state.logsCache); else showToast('info','No logs to export'); }; }catch(e){ setStatus('Logs load failed: '+e.message,false); }}
  function bindNav(){ $$('.sidenav button').forEach(b=>b.addEventListener('click', ()=>{ switchTab(b.dataset.tab); if(b.dataset.tab==='overview') loadOverview(); if(b.dataset.tab==='products') loadProducts(); if(b.dataset.tab==='gallery') loadGallery(); if(b.dataset.tab==='payments') loadPayments(); if(b.dataset.tab==='logs') loadLogs('price'); })); $$('#tab-logs .tabs button').forEach(b=>b.addEventListener('click', ()=>{ $$('#tab-logs .tabs button').forEach(x=>x.classList.toggle('active', x===b)); loadLogs(b.dataset.log); })); $('#pay-filter').addEventListener('click', loadPayments); $('#signOut').addEventListener('click', async ()=>{ try{ await fetchJson('/auth/logout', {}, { method:'POST' }); localStorage.removeItem('adminToken'); location.href = 'login.html'; }catch(e){ showToast('error','Sign out failed: '+e.message); } }); }
  async function bootstrap(){ bindNav(); $('#buildId').textContent = 'admin-v1.' + new Date().toISOString().slice(0,10); await getSession(); try{ await loadOverview(); }catch(e){ setStatus('Unable to connect. Check scriptUrl in config.', false); } }
  document.addEventListener('DOMContentLoaded', bootstrap);
})();
