
const ALLOWLIST = ['wykiesautomation@gmail.com'];
let currentUser = null; let role = 'Viewer';
window.onGoogleSignIn = (resp)=>{ try{ const payload = JSON.parse(atob(resp.credential.split('.')[1])); if(!ALLOWLIST.includes(payload.email)){ alert('Access denied'); google.accounts.id.disableAutoSelect(); return; } currentUser = {email: payload.email, name: payload.name}; const pass = (document.getElementById('passphrase').value||''); document.getElementById('signin').style.display='none'; document.getElementById('app').style.display='block'; initApp(pass); }catch(e){ alert('Sign-in failed'); } };
document.getElementById('signout').addEventListener('click', ()=>{ google.accounts.id.disableAutoSelect(); location.reload(); });
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
function switchTab(id){ document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active', b.dataset.tab===id)); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active', t.id==='tab-'+id)); }
async function initApp(passphrase){ const cfg = await (await fetch('../public/assets/js/config.json')).json().catch(()=>({})); const r = await fetch(cfg.appsScriptBase + '?action=role&pass='+encodeURIComponent(passphrase||'')) .then(r=>r.json()).catch(()=>({role:'Viewer'})); role = r.role || 'Viewer'; showToast('Logged in as ' + role); await loadProducts(cfg); await loadPriceLog(cfg); await loadPayments(cfg); await loadGallery(cfg); }
function showToast(msg){ const t=document.getElementById('toast'); t.textContent=msg; t.style.display='block'; setTimeout(()=>{t.style.display='none';}, 2000); }
async function loadProducts(cfg){ const products = await (await fetch('../public/assets/js/products.json')).json(); document.getElementById('m-prod').textContent = products.length; document.getElementById('m-act').textContent = products.filter(p=>p.active).length; const rows = document.getElementById('prod-rows'); rows.innerHTML=''; products.forEach(p=>{ const tr=document.createElement('tr'); tr.innerHTML = `<td>${p.sku}</td><td>${p.name}</td><td>R ${p.price}</td><td>${p.summary||''}</td><td>${p.imageUrl||''}</td><td>${p.active?'yes':'no'}</td><td><button class='btn small' data-edit='${p.sku}' ${role!=='Admin'?'disabled':''}>Edit</button></td>`; rows.appendChild(tr); }); rows.addEventListener('click', async (e)=>{ const btn=e.target.closest('button[data-edit]'); if(!btn) return; const sku=btn.getAttribute('data-edit'); if(role!=='Admin'){return;} showToast('Edit ' + sku + ' (coming soon)'); }); }
async function loadPriceLog(cfg){ const pl = await (await fetch('../public/assets/js/price-log.json')).json(); const plRows = document.getElementById('pricelog-rows'); plRows.innerHTML=''; pl.forEach(r=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${new Date(r.timestamp).toLocaleString()}</td><td>${r.sku}</td><td>${r.oldPrice}</td><td>${r.newPrice}</td><td>${r.changedBy||''}</td><td>${r.sourceIP||''}</td>`; plRows.appendChild(tr); }); document.getElementById('m-chg').textContent = pl.filter(x=>Date.now()-new Date(x.timestamp).getTime() < 30*24*60*60*1000).length; }
async function loadPayments(cfg){ const payRows = document.getElementById('pay-rows'); payRows.innerHTML = `<tr><td colspan='9' class='muted'>No payments yet.</td></tr>`; const recRows = document.getElementById('recent-pay'); recRows.innerHTML = `<tr><td colspan='8' class='muted'>No recent payments.</td></tr>`; }
async function loadGallery(cfg){ const tbl=document.getElementById('gallery-rows'); tbl.innerHTML=''; const list = await (await fetch('../public/assets/img/gallery/gallery.json')).json(); list.forEach((s,idx)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td><img src='${s.src}' alt='${s.alt||''}' style='width:120px;height:80px;object-fit:cover'></td><td contenteditable='${role==='Admin'}'>${s.alt||''}</td><td>${idx}</td><td><button class='btn small' data-up='${idx}' ${role!=='Admin'?'disabled':''}>Up</button> <button class='btn small' data-dn='${idx}' ${role!=='Admin'?'disabled':''}>Down</button></td>`; tbl.appendChild(tr); }); }
